name: 'Setup Eigen3'
description: 'Setup workflow with Eigen3'
inputs:
  version:
    description: 'Eigen3 version'
    required: false
    default: latest
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}