name: Test Eigen3 setup
on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build_test_project:
    runs-on: ${{ matrix.os }}
    name: Build project with Eigen3
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Eigen3
        uses: ./
        id: install-eigen3
        with:
          version: 3.4.0

      - name: Check Eigen cmake module
        run: cmake --find-package -DNAME=Eigen3 -DCOMPILER_ID=GNU -DLANGUAGE=C -DMODE=EXIST

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/tests -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE
